development:
  aws_key: ###
  aws_secret: ###
  aws_bucket: ###
  dropbox_key: p9rbwo0f7pes0zv
  dropbox_secret: n3z1rldbsppv7jg
  dropbox_redirect_uri: 'http://localhost:3000/sessions/create'
  diffbot: 2c6452c40aed5176969bdc31587b5269

staging:
  aws_key: ###
  aws_secret: ###
  aws_bucket: ###
  dropbox_key: p9rbwo0f7pes0zv
  dropbox_secret: n3z1rldbsppv7jg
  dropbox_redirect_uri: 'http://localhost:3000/sessions/create'
  diffbot: 2c6452c40aed5176969bdc31587b5269

production:
  aws_key: ###
  aws_secret: ###
  aws_bucket: ###
  dropbox_key: p9rbwo0f7pes0zv
  dropbox_secret: n3z1rldbsppv7jg
  dropbox_redirect_uri: 'http://localhost:3000/sessions/create'
  diffbot: 2c6452c40aed5176969bdc31587b5269