development:
  access_key_id: AKIAIOL5KEKMUT7VNYXA
  secret_access_key: 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
  bucket: barrow-dev
  dropbox_key: p9rbwo0f7pes0zv
  dropbox_secret: n3z1rldbsppv7jg
  dropbox_redirect_uri: 'http://localhost:5000/sessions/create'
  diffbot: 2c6452c40aed5176969bdc31587b5269

staging:
  aws_key: ###
  aws_secret: ###
  aws_bucket: ###
  dropbox_key: p9rbwo0f7pes0zv
  dropbox_secret: n3z1rldbsppv7jg
  dropbox_redirect_uri: 'http://localhost:5000/sessions/create'
  diffbot: 2c6452c40aed5176969bdc31587b5269

production:
  aws_key: ###
  aws_secret: ###
  aws_bucket: ###
  dropbox_key: p9rbwo0f7pes0zv
  dropbox_secret: n3z1rldbsppv7jg
  dropbox_redirect_uri: 'http://localhost:5000/sessions/create'
  diffbot: 2c6452c40aed5176969bdc31587b5269